### ISSUE TITLE
Running locally with docker results in GUI which does not update unless refreshed.

### ISSUE THREAD

**Issue by Kvothe-The-Bloodless** [halogenandtoast/ArkhamHorror#2678]
Ubuntu 24.04 (as well as 22.02)L: 
Installed docker and docker compose and dependencies and ran the app.

When I go to http://localhost:3000/ I can start a game and it works except that after I click somewhere the situation doesn't update until I refresh. I.e. I would have to refresh after every single click to make the GUI update. (Also tried different browsers.)

**Comment by chozekun** [comment]
I've encountered the exact same issue as you.
To resolve it, I performed a binary search through the tags on https://hub.docker.com/r/halogenandtoast/arkham-horror/tags to identify the problematic Docker image.

The following Docker image should fix the problem:
`halogenandtoast/arkham-horror:9442a4a8d6ec3b10d7aec00fcc9701a5c599a792`
This is the last image in which the issue does not occur.

I suspect that the problem started appearing in versions after the image below:
`halogenandtoast/arkham-horror:6acb501aeef7baee471fcebfa5311cbb08494afa`

I have attached the error logs for debugging purposes.

```
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:31 +0000] "GET /api/v1/arkham/decks HTTP/1.1" 200 2 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:31 +0000] "GET /api/v1/site-settings HTTP/1.1" 200 16 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:31 +0000] "GET /api/v1/whoami HTTP/1.1" 404 23 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:39 +0000] "POST /api/v1/register HTTP/1.1" 200 148 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:39 +0000] "GET /api/v1/whoami HTTP/1.1" 200 82 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:39 +0000] "GET /api/v1/whoami HTTP/1.1" 200 82 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
db-1     | 2025-09-16 03:51:39.591 UTC [72] ERROR:  relation "notifications" does not exist at character 40
db-1     | 2025-09-16 03:51:39.591 UTC [72] STATEMENT:  SELECT "id", "body", "created_at" FROM "notifications" ORDER BY "created_at" DESC
web-1    | 16/Sep/2025:03:51:39 +0000 [Error#yesod-core] SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"notifications\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""} @(yesod-core-1.6.27.1-Gm8dnn9XJEtGHJT8ZiD1oZ:Yesod.Core.Class.Yesod src/Yesod/Core/Class/Yesod.hs:703:6)
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:39 +0000] "GET /api/v1/notifications HTTP/1.1" 500 214 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:39 +0000] "GET /api/v1/arkham/games HTTP/1.1" 200 2 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:39 +0000] "GET /api/v1/arkham/investigators HTTP/1.1" 200 747 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:39 +0000] "GET /api/v1/arkham/decks HTTP/1.1" 200 2 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:42 +0000] "POST /api/v1/arkham/decks/validate HTTP/1.1" 200 2 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:42 +0000] "POST /api/v1/arkham/decks HTTP/1.1" 200 604 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
db-1     | 2025-09-16 03:51:43.491 UTC [73] ERROR:  relation "notifications" does not exist at character 40
db-1     | 2025-09-16 03:51:43.491 UTC [73] STATEMENT:  SELECT "id", "body", "created_at" FROM "notifications" ORDER BY "created_at" DESC
web-1    | 16/Sep/2025:03:51:43 +0000 [Error#yesod-core] SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"notifications\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""} @(yesod-core-1.6.27.1-Gm8dnn9XJEtGHJT8ZiD1oZ:Yesod.Core.Class.Yesod src/Yesod/Core/Class/Yesod.hs:703:6)
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:43 +0000] "GET /api/v1/notifications HTTP/1.1" 500 214 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:43 +0000] "GET /api/v1/arkham/games HTTP/1.1" 200 2 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:44 +0000] "GET /api/v1/arkham/decks HTTP/1.1" 200 606 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:46 +0000] "POST /api/v1/arkham/games HTTP/1.1" 200 1437 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:46 +0000] "GET /api/v1/arkham/games/6ff2e6e4-502b-4cee-bf60-255363d9dbb3 HTTP/1.1" 200 1528 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:46 +0000] "GET /api/v1/arkham/games/6ff2e6e4-502b-4cee-bf60-255363d9dbb3?token=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjEuNzU3OTk0Njk5NTQ1NTE4MDg3ZTksImlzcyI6ImFya2hhbSIsImp3dCI6MX0.STsLYDIDDgMWNDwc0rcfWOp9lIFIvNL0mcE_p4tZ1Cs HTTP/1.1" 500 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:46 +0000] "GET /api/v1/arkham/decks HTTP/1.1" 200 606 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:46 +0000] "GET /api/v1/arkham/cards?includeEncounter HTTP/1.1" 200 4942043 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 16/Sep/2025:03:51:57 +0000 [Warn] CloseRequest 1000 "" @(arkham-api-0.0.0-B96SuOcdJHlFAWBmADKgUj:Api.Handler.Arkham.Games.Shared library/Api/Handler/Arkham/Games/Shared.hs:80:20)
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:58 +0000] "GET /api/v1/site-settings HTTP/1.1" 200 16 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:58 +0000] "GET /api/v1/whoami HTTP/1.1" 200 82 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:58 +0000] "GET /api/v1/arkham/games/6ff2e6e4-502b-4cee-bf60-255363d9dbb3 HTTP/1.1" 200 17447 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:58 +0000] "GET /api/v1/arkham/cards?includeEncounter HTTP/1.1" 200 4942043 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 127.0.0.1 - - [16/Sep/2025:03:51:58 +0000] "GET /api/v1/arkham/games/6ff2e6e4-502b-4cee-bf60-255363d9dbb3?token=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjEuNzU3OTk0Njk5NTQ1NTE4MDg3ZTksImlzcyI6ImFya2hhbSIsImp3dCI6MX0.STsLYDIDDgMWNDwc0rcfWOp9lIFIvNL0mcE_p4tZ1Cs HTTP/1.1" 500 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
web-1    | 16/Sep/2025:03:51:57 +0000 [Warn] CloseRequest 1000 "" @(arkham-api-0.0.0-B96SuOcdJHlFAWBmADKgUj:Api.Handler.Arkham.Games.Shared library/Api/Handler/Arkham/Games/Shared.hs:80:20)
web-1    | 127.0.0.1 - - [16/Sep/2025:03:52:00 +0000] "GET /api/v1/arkham/games HTTP/1.1" 200 315 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
db-1     | 2025-09-16 03:52:00.036 UTC [76] ERROR:  relation "notifications" does not exist at character 40
db-1     | 2025-09-16 03:52:00.036 UTC [76] STATEMENT:  SELECT "id", "body", "created_at" FROM "notifications" ORDER BY "created_at" DESC
web-1    | 16/Sep/2025:03:52:00 +0000 [Error#yesod-core] SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"notifications\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""} @(yesod-core-1.6.27.1-Gm8dnn9XJEtGHJT8ZiD1oZ:Yesod.Core.Class.Yesod src/Yesod/Core/Class/Yesod.hs:703:6)
web-1    | 127.0.0.1 - - [16/Sep/2025:03:52:00 +0000] "GET /api/v1/notifications HTTP/1.1" 500 214 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
```

**Comment by Kvothe-The-Bloodless** [comment]
"docker compose exec db psql -U postgres -d arkham-horror-backend -c \
"create table notifications (id serial primary key, body text, created_at timestamp);
 alter table users add column admin boolean default false;"
ERROR:  column "admin" of relation "users" already exists"

The issue remains.

**Comment by Kvothe-The-Bloodless** [comment]
Your command gave an error `/usr/lib/postgresql/14/bin/psql: option requires an argument -- 'c'`

I ran instead `docker compose exec db psql -U postgres -d arkham-horror-backend -c "create table notifications (id serial primary key, body text, created_at timestamp);" which seems to have done something. But still it is not updating without a refresh. I don't know how to "look for javascript errors".
`

For the javascript errors I did the following. Opened developers tools - Console. Saw nothing. Refreshed. Saw nothing.

**Comment by halogenandtoast** [comment]
You can try:

> docker compose exec -T db psql -U postgres -d arkham-horror-backend < setup.sql

This would create all tables, but they will be empty and you'll need to register again.

**Comment by Kvothe-The-Bloodless** [comment]
This does not appear to have helped.

```
user@ubuntu24.04:~/GitRepos/ArkhamHorror$ docker compose down -v
[+] Running 6/6
 ✔ Container arkhamhorror-redis-1  Removed
 ✔ Container arkhamhorror-web-1    Removed
 ✔ Container arkhamhorror-db-1     Removed
 ✔ Volume arkhamhorror_redis-data  Removed
 ✔ Volume arkhamhorror_pgdata      Removed
 ✔ Network arkhamhorror_default    Removed

user@ubuntu24.04:~/GitRepos/ArkhamHorror$ docker compose up -d
[+] Running 6/6
 ✔ Network arkhamhorror_default      Created
 ✔ Volume "arkhamhorror_redis-data"  Created
 ✔ Volume "arkhamhorror_pgdata"      Created
 ✔ Container arkhamhorror-db-1       Started
 ✔ Container arkhamhorror-redis-1    Started
 ✔ Container arkhamhorror-web-1      Started

user@ubuntu24.04:~/GitRepos/ArkhamHorror$ docker compose exec -T db psql -U postgres -d arkham-horror-backend < setup.sql
SET
...
CREATE EXTENSION
COMMENT
ERROR:  function "check_no_higher_step_exists" already exists ...
ERROR:  relation "arkham_decks" already exists
...
ERROR:  multiple primary keys for table "users" are not allowed
...

```

Or with

```
docker compose exec -T db bash -lc 'until pg_isready -U postgres -d postgres; do sleep 1; done'
docker compose exec -T db psql -U postgres -c 'DROP DATABASE IF EXISTS "arkham-horror-backend";'
docker compose exec -T db psql -U postgres -c 'CREATE DATABASE "arkham-horror-backend";'
docker compose exec -T db psql -U postgres -d arkham-horror-backend < setup.sql
```
I get no errors but either way the gui does not update.

**Comment by halogenandtoast** [comment]
Yeah I don't know what to do to debug this further. The website itself runs off the docker images so they work under normal conditions.

> Opened developers tools - Console. Saw nothing. Refreshed. Saw nothing.

This would have been were javascript errors occur, but you would need to open the console, then do something that results in the UI not updating and seeing if anything gets printed there. If there really is nothing than I don't really have anything to go on to help. It could be that you already have something running on the port docker is using?

You could try this, right click, his inspect, go to network, for the sockets section and find the one socket connect like below:

<img width="1081" height="302" alt="Image" src="https://github.com/user-attachments/assets/4d8f06fb-eef9-4c8b-85a0-31a320e07b83" />

When you click on it make sure messages are selected and you should see the following

<img width="1235" height="537" alt="Image" src="https://github.com/user-attachments/assets/34ff8d37-5c02-40dc-a4da-8d360b054691" />

Do something that should update the game state and you should see a message, click on it and how what the result is. If it's something other than hopefully it illuminates what the issue is:

<img width="1239" height="231" alt="Image" src="https://github.com/user-attachments/assets/7affd7ac-415c-4acc-b6cc-9f70832bbc76" />
